### PR TITLE
Report additional comments

### PR DESCRIPTION
**Pull request by nbiton**
This enables adding "Additional Comments" to reports while they are in draft mode

### CODE REVIEW

**Comment by nbiton** [comment]
screenshot from 2018-08-15 14-15-32
@franck-boullier any objection to merge this?

**Comment by franck-boullier** [comment]
> any objection to merge this?

No objection to merge this BUT we need to make sure that https://github.com/unee-t/bugzilla-customisation/pull/72 is approved, merged and tag released first or this will will not work on the DEV, DEMO and PROD envo.
I am still waiting for @kaihendry 's review on that

@nbiton, please wait until this is done before you merge

**Comment by franck-boullier** [comment]
@nbiton do you also plan to allow the user to add pictures there too or will this be done in another PR?

**Comment by nbiton** [comment]
Small tweak to how additional comments appear on finalized report view

**Comment by nbiton** [comment]
https://github.com/unee-t/bugzilla-customisation/pull/72 was just merged, so I'm merging this too

**Pull request merged**
