### PR TITLE
feat: tabbed layout for report's draft view #486

### PR DESCRIPTION
**Pull request by nbiton**
screenshot from 2018-10-31 09-22-39
screenshot from 2018-10-31 09-22-55

Added animated swipeable tabs to the report's draft view. The new header tabs are a custom built component created to fit the design.

### CODE REVIEW

**Comment by nbiton** [comment]
@franck-boullier ready for functional review

**Comment by nbiton** [comment]
> On Android Phone when the keyboard slide up the "remark and comment" section is hidden (tested on galaxy S8)

Good point. I haven't tested it with tge keyboard open until you mentioned it. How should we resolve this? Make the entire view scrollable and not just the tabs' contents?

**Comment by nbiton** [comment]
> After creating a case user is sent back to the 'Overview' tab. It'll be best that user stays on the 'Case' tab

Noted. It requires making the tabs url-bound which is slightly more complex, but doable

**Comment by franck-boullier** [comment]
> How should we resolve this? Make the entire view scrollable and not just the tabs' contents?

Not sure about this TBH ---> I'll go with your recommendation

**Comment by nbiton** [comment]
> I am now unable to go to any unit page in the Heroku app (endless page load) logged as Lionel 🤔

That appears to only happen with units that were created on DEV and not the PR app.
screenshot_20181031-143945_chrome
This one works for example (I just created it for this text). Therefore, this bug is probably unrelated to this PR and more likely due to other recent changes to the unit view, which are dependant on unit meta data which would be missing in this case. 
This PR had no effect on the unit view.

**Comment by franck-boullier** [comment]
> That appears to only happen with units that were created on DEV and not the PR app.

That's weird: I created Test Unit 2 in the PR and I can access it anymore now

**Comment by franck-boullier** [comment]
Just tried to create a new unit in the PR and I now have an error message "Unit Creation API Lambda error"...

**Comment by nbiton** [comment]
> Just tried to create a new unit in the PR and I now have an error message "Unit Creation API Lambda error"...

I'll have another go at it now while looking at the logs

**Comment by franck-boullier** [comment]
Error does not appear in the DEV: I am able to create a new unit without the lambda API error.

**Comment by nbiton** [comment]
> I'll have another go at it now while looking at the logs

Just did another test and it worked with no issues.
I don't have access to past error logs on PR apps unfortunately. (only live)

@kaihendry can we pull the error logs from the lambda somehow?

**Comment by nbiton** [comment]
@franck-boullier Checked with @kaihendry and there are no errors logged during that time. Can you reproduce the same error again, and if so trace back the steps which lead you to it?

**Comment by franck-boullier** [comment]
@nbiton build has failed ---> does it make sense for me to test it?

**Comment by franck-boullier** [comment]
>  Can you reproduce the same error again, 

Nope I cannot reproduce the error. It works now, I'm able to create a unit... Weird...

Also on the initial error (I am now unable to go to any unit page in the Heroku app - endless page load) logged as Leonel), I can confirm that it appears to only happen with units that were created on DEV and not the PR app.

**Comment by nbiton** [comment]
> @nbiton build has failed ---> does it make sense for me to test it?

Yes, shouldn't be a problem. It's just a non-critical lint error. I should be able to fix it later

**Comment by franck-boullier** [comment]
New version is now scrollable so it's possible to see the 'Remark and Comment' section if the user scrolls up.

# Suggestion for improvement:

When the user start typing in that section auto scroll the section to the top of the screen so user does not have to scroll

**Comment by nbiton** [comment]
> When the user start typing in that section auto scroll the section to the top of the screen so user does not have to scroll

Now that's implemented not only in the report's draft view, but in nearly every form's text inputs :tada:

**Comment by franck-boullier** [comment]
That works for me.
@nbiton OK to merge.

# minor suggestion (OK to merge without this anyway)

instead of auto scrolling the section to the top of the screen when the user starts typing, can we auto scroll when the section is selected/highlighted instead?
If this take time to implement then we'll ignore that for now

**Comment by nbiton** [comment]
> instead of auto scrolling the section to the top of the screen when the user starts typing, can we auto scroll when the section is selected/highlighted instead?
If this take time to implement then we'll ignore that for now

I'm not sure when a section is "selected/highlighted" but I guess we can discuss it separately. Merging it as it is

**Pull request merged**
