### PR TITLE
Scripts to get an overview of user base and unit MetaData

### PR DESCRIPTION
**Pull request by kaihendry**
These are for me, but someone else might find them useful? It assumes the AWS profiles of uneet-{dev,demo,prod} have been set up.

### CODE REVIEW

**Comment by nbiton** [comment]
Shouldn't scripts like these be a part of a repository like [unee-t/bz-database](https://github.com/unee-t/bz-database) and not *frontend*?

**Comment by franck-boullier** [comment]
> Shouldn't scripts like these be a part of a repository like unee-t/bz-database and not frontend?

I would agree that this probably does not belong to front end but it doesn't belong to bz-database either --->  unee-t/bz-database is for the underlying MariaDB of the BZ installation.

These scripts are for Mongo.
Do we want/need to create a dedicated repo for all the Mongo related stuff?

**Comment by kaihendry** [comment]
Perhaps like https://github.com/unee-t/bugzilla-customisation/tree/master/db but bz has nothing to do with Mongo queries, does it?

**Comment by franck-boullier** [comment]
> bz has nothing to do with Mongo queries, does it?

That is correct: bz has nothing to do with Mongo

**Comment by franck-boullier** [comment]
@kaihendry so what are we doing for this?

**Comment by kaihendry** [comment]
I'll put these somewhere else.

**Pull request closed without merging**
