### PR TITLE
feat: allow signup with promo codes

### PR DESCRIPTION
**Pull request by nbiton**
image

### CODE REVIEW

**Comment by nbiton** [comment]
@franck-boullier I created two promo codes on the review app DB, for you to test:
"promo-code" (Works)
"expired" (Expired)

**Comment by franck-boullier** [comment]
promo code is case sensitive.
This is an inconvenience because some user will type the promo code instead of copy/pasting it.

Since Android automatically capitalize the 1st letter of any line, the promo code is displayed as invalid.

Possible solution: is it difficult to make the promo code case insensitive?

**Comment by nbiton** [comment]
Should be easy... checking now

**Comment by nbiton** [comment]
The last commit should fix it

**Pull request merged**
