### PR TITLE
fix: removed package-lock.json andadd to gitignore

### PR DESCRIPTION
**Pull request by sophieyang0813**

### CODE REVIEW

**Comment by kaihendry** [comment]
Instead of creating this new PR with a new branch sophieyang0813:delete-package-json, please just update sophieyang0813:DummyUser with the commit.

**Comment by sebdeckers** [comment]
@kaihendry This change is unrelated to #294 . I explained to @sophieyang0813 that it is (socially and technically) easier to get PRs landed when you avoid including *drive-by* changes.

**Comment by nbiton** [comment]
I still think that the benefits of package-lock.json outweigh the disadventages.
We need it to make sure no breaking changes are introduced by npm packages minor updates between builds.
For consistency, we can run "meteor npm install" (meteor has a packaged npm included) locally which would ensure better that the generated json matches the used version of npm.

**Comment by sebdeckers** [comment]
Apologies for the bike-shedding.

Always using `meteor npm install` is not something I'm familiar enough with, but sounds reasonable.

FYI newer versions of npm have integrated reporting of vulnerabilities (I think based on snyk). Should be interesting to run that on this project. 🙈

**Comment by nbiton** [comment]
Closing this as the matter was resolved in #294 :+1:

**Pull request closed without merging**
