### PR TITLE
Add missing assignee

### PR DESCRIPTION
**Pull request by nbiton**
Answers #99 .
Includes all the code from the 'edit-case-status' branch which wasn't merged yet.

### CODE REVIEW

**Comment by franck-boullier** [comment]
just for the records, the 'edit case status' functionality is not working fully yet: switching to a 'closed' status generates an error (resolution is not defined)

**Comment by franck-boullier** [comment]
# Test done:
As Leonel Agent for unit 284
1- Create a case in demo unit 284
2- Assign the case to the tenant

# Expected result:
A dialogue appear informing that there are no registered tenant yet and that one must be created PASSED
Once email for the tenant is entered, 
* case is created
* invitation is generated and waiting for processing in the invitation API

# Actual result: 
image
This seems to be a permission issue. I need to make sure that temporary users have permission to edit cases too.

# Next step:
Franck to
1- Edit the permission in the dev for the user temporary.tenant.dev@unee-t.com' so that this user can edit cases for unit 284
2- Check that this fixes the issue
3- IF this fixes the issue, then update the unit creation script to make sure the temporary users have the right to edit cases for all the new units.

**Comment by franck-boullier** [comment]
@nbiton the solution described above did NOT fix the API error.
I need to better understand what the MEFE is trying to do to find a solution to the issue.

# What I tried:
* Verify that user 'temporary.tenant.dev@unee-t.com' has permission to edit a case (it has)
* grant the user 'temporary.tenant.dev@unee-t.com' permission to edit the product/unit 284
Still, the API error appears
image

**Comment by franck-boullier** [comment]
new change: in the BZ back end grant permission to can-see-cases in unit 284 to user  'temporary.tenant.dev@unee-t.com' 
This fixed the issue: 
* the case is created.
* Assignee is franck- test user. the existing user associated to the email entered in the invitation.

#Issue:

## misleading error message:
a better error message should be "[user] is not able to access cases in the [unit name] unit and can't be associated to any case in this unit."

## Assignee appears as pending:
In the list of possible assignees for this case, the current assignee appears as 'pending'. It is unclear why.

image

@nbiton will this change once the invitation is processed?

**Comment by franck-boullier** [comment]
# Test continued:
* Check that an invitation has been added to the list of invitation to process FAIL -> there is no Valid token for the pr 168 in heroku
@nbiton, can you please create one?

# Pending tests:
* Process the invitation check that no error appear
* Check that invited person has received the email
* Check that the invited person is not with a 'pending' status in the MEFE anymore.

**Comment by nbiton** [comment]
The API error message that you saw is generated by BZ. The MEFE code just lets it pass through, so there isn't much to change about it. I think it would've been shown before this feature as well, as the only addition, from an API perspective, is the creation of the invitation after a case is created. There is nothing new that modifies anything via BZ API. 
I'll PM you the access token for this instance.

**Comment by franck-boullier** [comment]
# Test continued:
* Process the invitation check that no error appear PASSED
* Check that invited person has received the email FAIL, no email received. @nbiton is the email engine working on the Heroku deployments?
* Check that the invited person is not with a 'pending' status in the MEFE anymore. FAIL: it is not possible to access cases anymore...
Error is
image

@nbiton any idea what might be happening?

**Comment by franck-boullier** [comment]
More information about the issue:
When I try to access the case as the user who just has been invited, this is the error message I get
image

Note: it is possible to access a case in another unit.

**Comment by franck-boullier** [comment]
More info about the issue:
It is possible to access the case (61924) via dev.case.unee-t.com but NOT via the heroku deployment.

**Comment by nbiton** [comment]
The last commit should fix the remaining issues for editing a status (issue #108)

**Comment by franck-boullier** [comment]
@nbiton, this is not working:

# Test done:
* Create a case
* Assign it to a role that has no 'real' user yet

# Result:
Error message:
image

After clicking on the 'OK' button we are going back to the case creation page.
image

**Comment by franck-boullier** [comment]
@nbiton "The last commit should fix the remaining issues for editing a status (issue #108)"
Unfortunately, this is not the case:

# Test done:
On case #58260 change the status from IN_PROGRESS to RESOLVED

# Result of the test: 
The status is still IN_PROGRESS

See screen capture with console output
image

**Comment by nbiton** [comment]
screenshot from 2018-03-22 19-33-35
Once I set these 3 to off, there's no error when changing to a status that closes the bug. I thought they were already set to 'off' because one of the comments that you left on the previous PR...

**Comment by nbiton** [comment]
Re: one comment before that -
I'm not sure what went wrong there, I tried something that seems very similar, but it worked for me. (Tested on the PR app).
screenshot from 2018-03-22 19-43-15

**Comment by franck-boullier** [comment]
OK I'll try to test again just now

**Comment by franck-boullier** [comment]
@nbiton I tested again the change resolution to 'RESOLVED'
# The test:
* Check that the BZ configuration is OK in the [dev instance](https://dev.dashboard.unee-t.com/editparams.cgi?section=bugchange) DONE
image
* Log in to the [Heroku deployment of the MEFE](https://unee-t-pr-168.herokuapp.com/case/61825/details) as Franck (administrator)
* Go to 1 case (case 61825)
* Change the status of the case from 'CONFIRMED' to 'RESOLVED'

# Test result:
Error is still there, the status of the case is NOT updated.
image

**Comment by franck-boullier** [comment]
Testing the invitation issue again.

# The test:
* go to the [Heroku deployment of the MEFE](https://unee-t-pr-168.herokuapp.com/case).
* log in as Franck (administrator) OK
* Create a new case in unit P_11_01-21_2 - #127
* Invite a new user as the tenant
* New user is also the occupant fort the unit
* New user does NOT exist in Unee-T yet.

# Test result:
Same error as before: 
image

**Comment by franck-boullier** [comment]
@nbiton "I'm not sure what went wrong there, I tried something that seems very similar, but it worked for me. (Tested on the PR app)."

Can you try to document your procedure so we can identify what you and I are doing differently?

**Comment by franck-boullier** [comment]
Latest deployment of the BZ front end fixed the 'closed status' issue. It is now possible for me to mark a case as RESOLVED

**Comment by franck-boullier** [comment]
# Test done
On a test unit (with no # in the unit name)
* Create a case DONE
* Assign to tenant DONE
* Tenant is franck.boullier@gmail.com DONE
* Case is created with no issue
## Process invitation
* Invitation is visible PASSED
* Process invitation DONE - No error
* check email is received
* check user is correctly assigned in the MEFE as the invitor go to the unit -> case 
Error message:
image

**Comment by franck-boullier** [comment]
email from the previous invite was not received...

**Comment by franck-boullier** [comment]
more info on the issue: I am NOT able to access the case in the heroku deployment BUT I AM able to access the same case in the dev.case interface.

**Comment by nbiton** [comment]
Last issue seems to be related to the Mongo instance used for the PR apps. We're going to merge it to master and continue testing on the dev environment.

**Pull request merged**
