### PR TITLE
Report attachments

### PR DESCRIPTION
**Pull request by nbiton**

### CODE REVIEW

**Comment by nbiton** [comment]
screenshot from 2018-08-20 15-33-17
I got the attachment uploading fully working with no feature parity with the cases' attachments- there's a preview, preloader and a "retry" button in case the upload fails (loss of connection/ network issues).
This PR is ready for a final review and then can be merged.

**Comment by franck-boullier** [comment]
This works as intended!

@nbiton a few suggestions before we merge. These are based on user feedback and also my own UX tests 😋 

# The current screen:
Today the screen looks like this:
image

# Suggested cosmetic changes:

## Detailed list of the suggested change:

- Move the __'Additional Comments'__ section right after the __'Attach photos'__ section
- Rename __'Additional Comments'__ to __'Remarks about the Unit'__
- Replace the text __'Would you like to report any issues with the unit'__ with the following text __'Report a defect which needs to be corrected or fixed'__.
- Rename the __'Attach photos'__ section to __'Attach Photos'__ (capital 'P' for consistency)

## Rationale for the change"
better differentiate 
- __'cases'__: a fix is expected ---> they are more complex/time consuming to create
- __'remarks'__: there is no expected fix, this is just captured for future reference and to make sure that the condition of the unit is properly documented.

## Mockup:

image


@nbiton if this takes more than 1 hour to implement these changes then we will take care of this in a separate PR.

@kiatlim and @michkwt any major objection to this change?
If no, can you please update the mockups accordingly in the Invision and in the RTB please.
That way I'll be able to update the screenshots on the website too

**Comment by franck-boullier** [comment]
Come to think of it, it might be better to replace the text __'Additional Comments'__ with __'Remarks and Comments'__ instead of  __'Remarks about the Unit'__ ---> more versatile...

**Comment by nbiton** [comment]
Btw, having the "save draft" button there won't leave much space for the "Preview" button once we have preview implemented. We'll have to figure out what to do about that

**Comment by franck-boullier** [comment]
>I made the adjustments, almost as requested...

:tada: 

> I made "save for later" be "Save draft" 

OK with me!

> and gave it a "secondary" color

Not a fan of the 'Pink' Button: it feels like we are breaking the consistency of our look and feel and introduction a new color to the palette too ---> I'd prefer to use the same logic that we have for the design of the 'Preview' Button

image

> BTW, having the "save draft" button there won't leave much space for the "Preview" button once we have preview implemented. We'll have to figure out what to do about that

Good point, but we'll figure that one out later in the PR to implement the Preview functionality...
@kiatlim and @michkwt can you have a look at this one?

> "Report a defect which needs to be corrected or fixed" -> "Is there any defect with the unit to report?". I find it more personal and engaging when it's still keeping the question form.

I  understand your point about asking a question.
I still believe that we need to be specific about the fact that this is for "defects which needs to be corrected or fixed" ---> this gives important information to the user about the nuances between remarks/comments and cases.
What about __"Is there any defect which needs to be corrected or fixed?"__

**Comment by franck-boullier** [comment]
Also can we caption the button "Save Draft" (capital 'D') for consistency too :blush:

**Comment by kiatlim** [comment]
I was thinking if we could put the save at the top beside the title instead. Since it will be an action that happens across all the screens during an inspection report, having a visible save icon may be more useful. 

Except the issue is i can't find a decent icon yet. 
image

**Comment by nbiton** [comment]
screenshot from 2018-08-21 17-28-51
Or this one, for the slightly younger generation :sweat_smile:

**Comment by franck-boullier** [comment]
> I was thinking if we could put the save at the top beside the title instead. Since it will be an action that happens across all the screens during an inspection report, having a visible save icon may be more useful.

@kiatlim I like that idea, let's go with this
@nbiton I like the 'save' icon above.

**Comment by franck-boullier** [comment]
'Save' is a familiar icon too (they use a similar one in Office) 
image

**Pull request merged**
