### PR TITLE
feat: error msg display

### LINKED ISSUE #206: Sign Up - "email already exist" error message should be displayed on screen
Signup of existing email, should show an error message

(Screenshot shows the "result" after clicking submit)
screen shot 2018-04-12 at 5 03 53 pm

Note that according to console.log, the API does respond appropriately for this.

screen shot 2018-04-12 at 5 05 21 pm

**Site Tested**
+ https://dev.case.unee-t.com/signup
+ https://demo.case.unee-t.com/signup

**Browser Tested**
+ Chrome

### PR DESCRIPTION
**Pull request by sophieyang0813**
This fixes #206. 'Email already exists' and 'REST API error' messages are displayed when errors are raised. 

screen shot 2018-08-07 at 3 57 43 pm

screen shot 2018-08-07 at 3 57 58 pm

### CODE REVIEW

**Comment by nbiton** [comment]
**On signup**, right?

**Comment by sophieyang0813** [comment]
Yes, this is on signup. 😄😄 I referred to login error to fix this issue.

**Comment by franck-boullier** [comment]
@sophieyang0813 can we change the message when the email address already exists and add a suggestion to reset the password and also add the link to the reset password page.

Something like "that email already exists in Unee-T. You can [reset your password](https://case.unee-t.com/forgot-pass) if needed"

**Comment by sophieyang0813** [comment]
@nbiton Good afternoon! This code is ready for a review. 

I implemented @franck-boullier 's request on adding a 'reset password' link in errorText. While code works, Material-ui TextField errorText throws a warning(not an error) for a mismatching proptype. It expects a string literal, not Link object (react-router-dom). I customized a prop validator in TextField (as suggested [here](https://github.com/mui-org/material-ui/issues/10845)), but it did not work perhaps due to a material ui version difference. 

Is this warning negligible given that the code works visually and functionally (the link goes to[ reset the password](https://case.unee-t.com/forgot-pass))? or what would you suggest 🤔? 

screen shot 2018-08-08 at 3 09 08 pm
screen shot 2018-08-08 at 3 09 20 pm

**Comment by nbiton** [comment]
@sophieyang0813 I think you should use the errorText as it is implemented in Material UI and just use the string "email already exists in Unee-T". **In addition**, you should add conditional rendering of the link just below the TextField, unrelated to `errorText`

**Pull request merged**
