### PR TITLE
Revise invite ui #198

### PR DESCRIPTION
**Pull request by nbiton**

### CODE REVIEW

**Comment by franck-boullier** [comment]
# Test done:
- Log in to the application: PASSED
- Go to a case
  - Change the assignee: check that no error and that the UX is updated to the new design
    - Assigned user exist: PASSED
    - Assigned user does not exist - invitation needs to be sent: PASSED
  - Invite a user in CC for the case:
    - The new UX is displayed: PASSED
    - It is possible to invite an existing user to a case: PASSED
    - It is possible to invite a new user to a case: FAIL.
image

# Misc Issues:
## Typos:
The text "invite or remove users" needs to be updated to "invite users"
image
## Behavior:
When we invite a user in CC to a case 
### Invite more users - Invitation seem to be send twice: 
  - Click on "invite user"
  - Tick the box next to an existing user (Celeste)
  - Click on "Send invitation"
  - Confirmation message appears - all is good so far.
  - Close the modal window (do NOT click on "invite another person"
  - Click on "Invite user" again
  - Expected result: the list of user who have not been invited to the case is displayed
  - Actual result: Unee-T acts as if the invitation to Celeste is sent one more time.
image

### Invitation with no user selected.
  - Click on "invite user"
  - DO NOT Tick any of the box next to an existing user
  - Click on 'Send invitation"
  - Expected result: Error message "please select a user to invite to this case"
  - Actual result: 
image

**Comment by franck-boullier** [comment]
@nbiton can we also include #182 in this PR? This should be super simple to do right?

**Comment by nbiton** [comment]
Please review again with the newly deployed fixes

**Comment by franck-boullier** [comment]
# Check that all previous reported bugs are taken care of:
Done
All reported issues fixed

# Minor issue:
When there is no user in the list, we need to change the message currently displayed:
image

**Comment by franck-boullier** [comment]
# Check that all previous reported bugs are taken care of:
Done
All reported issues fixed

# Minor issue:
When there is no user in the list, we need to change the message currently displayed:
image

**Comment by nbiton** [comment]
I'm changing the "empty" message to **"All the known users for this unit are already invited"** for the user invitation dialog and **"We couldn't find any existing users to assign"** for the user assignment dialog (but that would appear much less commonly)

**Comment by nbiton** [comment]
Failing due to an unrelated issue involving the latest node version. The failure will be fixed in a separate PR.

**Pull request merged**
