### PR TITLE
feat: Add a "Disabled Unit" tag for the disabled units in the `case` and `report` pages

### LINKED ISSUE #418: When a unit is disabled, replace the 'Add Case' link with 'Disabled Unit'
# The Problem:
When a unit is disabled, it is not possible to create new cases for that unit BUT existing cases are still visible in the 'Case' view.

We want to add a message/visual cue in the Case view to explain why the "Add Case" button is not available for some units (why it's not possible to add a case to these units).

# Suggested Solution:

image

@kiatlim if there is no issue with this suggetion, can you make sure that the design is updated in the RTM and also in Invision?
Thanks

# Background information:

We already touched upon this suggestion the conversation for PR #396 See @sophieyang0813 's comment about the current code:

----
Case view(case-explorer.jsx) and unit view (unit-explorer.jsx) are in different files, so I naturally thought this is a separate issue. For what I skimmed, case view and unit view have different 'add case' button displaying logic. One in unit view is displayed when current user id matches with metadata.ownerid, while one in case view is displayed with bzId(?). It can be a minor issue but it might not be an issue that can be fixed in 10 min.

@nbiton do we update the case view add button with unit view display logic (i.e. do I add same metadata to UnitMetaData in cases.jsx)? If yes, do I replace or keep bzId?

```
 {bzId && (
  <div className='no-shrink flex items-center'>
    <Link
      className='f6 link ellipsis ml3 pl1 mv1 bondi-blue fw5'
      to={`/case/new?unit=${bzId}`}>
      Add case
    </Link>
  </div>
)}
```
----

### PR DESCRIPTION
**Pull request by sophieyang0813**
This fixes #418 
@nbiton This code is ready for review.Thank you for suggesting a solution last time. `is_active` now makes sense 🌻

### CODE REVIEW

**Comment by franck-boullier** [comment]
This seems to work as expected although it's hard to tell: I don't understand why some units are displayed with neither the "add case" or "Unit Disabled" information...

I'm suspecting this is somewhat linked to Heroku using a different Mongo instance where these unit do not exist but I'm not too sure...

@nbiton any idea what might be the root cause of that?

image

**Comment by franck-boullier** [comment]
@nbiton is this OK to merge?

**Comment by nbiton** [comment]
Is this still relevant? If it is, the merge conflicts need to be resolved

**Comment by franck-boullier** [comment]
Yep this is still relevant 😉

**Comment by nbiton** [comment]
The question was addressed to @sophieyang0813 :sweat_smile: I wasn't sure if this was being worked on in a different branch/ PR

**Comment by sophieyang0813** [comment]
@nbiton I will get back to you on this today! 🌻

**Comment by sophieyang0813** [comment]
#645 addresses this

**Pull request closed without merging**
