### PR TITLE
feat: Automated invitations integration

### LINKED ISSUE #228: Call Web hook to process invites on new invite
https://invite{{STAGE}}.unee-t.com as documented in Postman under **Process invitations**.

Implemented at https://github.com/unee-t/invite

### PR DESCRIPTION
**Pull request by nbiton**
fixes #228 and #126

### CODE REVIEW

**Comment by nbiton** [comment]
Feel free to merge to master so you could test on dev once you're ready. (we can't test it on a Heroku review app currently)

**Comment by nbiton** [comment]
@kaihendry I just remembered that it's using a new env var to point to the Lambda's location. Is there anything else I need to do to be able to access that var?

**Comment by nbiton** [comment]
@franck-boullier go ahead and merge once you're ready to test it

**Comment by franck-boullier** [comment]
@nbiton https://unee-t-pr-247.herokuapp.com is not accessible for me 🤔

**Comment by nbiton** [comment]
Since there's no lambda API for review apps, you can only test it on dev. Merge it when you want to test it

**Pull request merged**
