### PR TITLE
Filter invalid notification recipients

### PR DESCRIPTION
**Pull request by nbiton**
In response to @kaihendry 's finding from this morning regarding invalid email recipients continuously being sent email notifications

### CODE REVIEW

**Comment by nbiton** [comment]
@kaihendry please feel free to merge this PR

**Comment by kaihendry** [comment]
Sorry, only just noticed this. Would be better if it would log whether it's invalid versus whether it's unverified.

**Comment by nbiton** [comment]
@kaihendry Please re-review. I think this should be sufficient?

**Comment by kaihendry** [comment]
LGTM

**Pull request merged**
