### PR TITLE
Deploying with METEOR_SETTINGS env var

### PR DESCRIPTION
**Pull request by nbiton**

### CODE REVIEW

**Comment by kaihendry** [comment]
Is this a secret btw?

**Comment by nbiton** [comment]
It's not

**Comment by kaihendry** [comment]
Did you check the `aws cli` command works? Was wondering if `--with-decryption` messes things up.

Actually I tested it myself, it doesn't seem to matter.

```
~$ aws --profile lmb-dev ssm get-parameters --names METEOR_SETTINGS --with-decryption --query Parameters[0].Value --output text
{
  "public": {
    "CLOUDINARY_URL": "https://api.cloudinary.com/v1_1/unee-t-dev/image/upload",
    "CLOUDINARY_PRESET": "knpnsowg"
  }
}
~$ aws --profile lmb-dev ssm get-parameters --names METEOR_SETTINGS --query Parameters[0].Value --output text
{
  "public": {
    "CLOUDINARY_URL": "https://api.cloudinary.com/v1_1/unee-t-dev/image/upload",
    "CLOUDINARY_PRESET": "knpnsowg"
  }
}

```

**Comment by nbiton** [comment]
Should I remove it just in case?

**Comment by kaihendry** [comment]
Yes, just remove it so it's obvious it's not a secret maybe. If you don't mind. I am not hugely bothered.

**Comment by nbiton** [comment]
It should be before our next deployment

**Pull request merged**
