### PR TITLE
Unit meta data UI integration

### LINKED ISSUE #230: PR227 - Unit description should come from the MEFE
The unit description is currently exported from the BZ side. This shouls be changed and we should use the Unit description from the MEFE.

image

### PR DESCRIPTION
**Pull request by nbiton**
Resolves #230

### CODE REVIEW

**Comment by franck-boullier** [comment]
@nbiton unable to test in the Heroku deployment: I think the data from the Mongo there are outdated compared to the data in the Mongo DB in the DEV/Staging.

Can we safely replace the data in the Mongo/heroku with the data from the Mongo/Dev?

**Comment by nbiton** [comment]
Yes. If you just copy over the UnitMetaData and UnitRolesData collections, there shouldn't be any issue

**Comment by nbiton** [comment]
But  it might be even faster and easier to test if you create a new unit via MEFE and then browse it

**Comment by franck-boullier** [comment]
# The test:

- Create a unit in MEFE: PASSED
- Check that unit name is not the same in MEFE and in BZFE (include suffix with BZ product id): PASSED

All works as intended

@nbiton is it OK to merge now?

**Comment by nbiton** [comment]
Did you check that you're getting all the right info in the unit's "overview" tab?

I also need to take care of the merge conflicts.

**Comment by franck-boullier** [comment]
> Did you check that you're getting all the right info in the unit's "overview" tab?

@nbiton I did and it works as intended there too :tada:

**Comment by nbiton** [comment]
Resolved the merge conflicts and included some refactoring for a small code duplication issue

**Pull request merged**
