### PR TITLE
Invite user to case

### PR DESCRIPTION
**Pull request by nbiton**
Not yet complete and functional, but the hardest part is over

### CODE REVIEW

**Comment by franck-boullier** [comment]
Not able to test the invitation mechanism.

What I tried:
got to an existing case in my list of cases:
image
Click on More info
image
Click on the icon to invite a user
image
I have no user to choose from

Tried to
1- click on 'Invite new user' button but nothing happens.
2- Enter an email address and click on 'Invite new user' button but nothing happens.

What am I doing wrong?

Is there anything I need to do

**Comment by nbiton** [comment]
The UI that should appear after clicking on "invite a new user" has not been implemented yet.
The list should contain all the users that appear in this unit's components under "default_assigned_to" and "default_qa_contact" (it was implemented before you mentioned that it isn't in use yet :sweat_smile: ). The list could be empty if no users are mentioned in the components in this way.

**Comment by franck-boullier** [comment]
OK Noted
I will:
1- create a new role for this test unit so that there is something to retrieve
2- Create a GH issue so that we can record that we need to:
    1- Remove 'default_qa_contact' from this selection
    2- Add the users that are in the 'component_cc' table for one of the roles/component for this unit to this selection.
    3- Add the users that are visible for this invitor for this unit (this is based on specific group membership) to this selection.

**Comment by franck-boullier** [comment]
See Issue #83

**Comment by franck-boullier** [comment]
Tests done:
in case 61886
Click on invite a new user DONE
Result - the window appears as expected
Add a new email DONE
choose the role for this new user in the unit DONE
if tenant or landlord a tick box appears to indicate if user is occupant or not PASSED
if NOT tenant or landlord a tick box does NOT appear to indicate if user is occupant or not PASSED
Click on Back button - PASSED (we go back to the previous page)
Click on the 'X' icon to close the window PASSED (the window is closed)
Click on 'Send invitation' nothing happens (yet)

@nbiton this look goo so far!

**Comment by franck-boullier** [comment]
Test done:
in case 61886
Click on invite a new user DONE
Result - the window appears as expected
Add a new email DONE
choose the role for this new user in the unit DONE
Click on 'Send invitation'. Result: after a short while confirmation windows appear PASSED
Close confirmation window. Result: the new invited user does NOT appear in the list (with status 'Invitation sent') see issue #86

Pending tests: see the invitation in the back end so it is possible to retrieve the information to run the invitation script (MVP)

**Comment by nbiton** [comment]
#86 is technically related to this PR, but we decided to do it later. Everything else seems fine, so... merging.

**Pull request merged**
