### PR TITLE
Report preview

### PR DESCRIPTION
**Pull request by nbiton**
Currently shows the preview in new '/preview' route.
The generated preview is based off live data if the report is not finalized. 
If it is finalized, it's based off the snapshot taken when it was finalized.

From now, image attachments are stored within the snapshot to make sure none were added since the moment of finalization.

### CODE REVIEW

**Comment by franck-boullier** [comment]
There seems to be an issue:

image


What I did: 
- go to an existing DRAFT report
- Click on the 'Preview' button

image

**Comment by nbiton** [comment]
@franck-boullier Your issue should be solved by the most recent commit, but there's another issue still causing a different error in some cases, which I need to resolve

**Comment by nbiton** [comment]
Ok, that last fix addressed something that was breaking the export in many scenarios. It should be mostly working now

**Comment by franck-boullier** [comment]
The problem reported here is fixed!

# The tests:

- Go to an existing DRAFT IR - click on preview - check that IR preview is visible - PASSED
- Check that the pictures from the IR are visible in the preview - PASSED
- Check that the cases created as part of the IR are visible in the preview - PASSED
- Check that the pictures added to a case associated to the IR are visible in the preview - PASSED

@nbiton so far so good!
Is there anything else that you think I can/should test?

**Comment by nbiton** [comment]
@franck-boullier I'll push some code to add a "Preview & Endorse" button on finalized reports very soon. Once that's in, you can test that finalized reports' export stays frozen even if the underlying cases are modified

**Comment by franck-boullier** [comment]
Minor issue:

When an IR is seen as a preview, there is a broken image link for the signature of the IR's creator (reporter)

image

**Comment by nbiton** [comment]
> Minor issue:
When an IR is seen as a preview, there is a broken image link for the signature of the IR's creator (reporter)

@kaihendry I'm sending an empty string as `data_uri` for each signature, as the signatures haven't been made yet. Is there a different value I can send so it won't show a broken image icon?

**Comment by kaihendry** [comment]
Ok, should print "UNSIGNED" now when no signature is sent. https://github.com/unee-t/inspectionreportgenerator/issues/4

**Comment by franck-boullier** [comment]
> Ok, should print "UNSIGNED" now when no signature is sent. unee-t/inspectionreportgenerator#4

Verified ---> issue is fixed in this PR

**Comment by nbiton** [comment]
Added the following:
screenshot from 2018-08-30 19-57-54
screenshot from 2018-08-30 19-58-22

The "Endorse" button is disabled due to the feature not being functional yet.
A part from that, I think this fully encompasses the "preview" feature, and can be merged as-is. (removing the WIP status from this PR).

**Comment by franck-boullier** [comment]
> I think this fully encompasses the "preview" feature, and can be merged as-is

OK I'll do the last test a little later tonight

@nbiton there seem to be some conflicts preventing the merge
See: `imports/ui/app.jsx`

**Comment by franck-boullier** [comment]
@nbiton OK to merge for me
We just need to resolve the merge conflicts first before we can merge

Great work! :+1:

**Comment by nbiton** [comment]
Conflicts resolved.
I just need to figure these out before we merge:
screenshot from 2018-08-31 11-31-24
https://github.com/nbiton/unee-t-fe/blob/report-review/imports/api/reports.js#L399
https://github.com/nbiton/unee-t-fe/blob/report-review/imports/api/reports.js#L406

Not sure where this data should come from. (from the BZ side)

**Comment by franck-boullier** [comment]
# For L 399 - `description` : 

@nbiton not sure about where this `description` is coming from?
Is it the mandatory BZ bug description which can't be empty when we create a BZ bug?
If this is the case, then this should be equal to the text in the MEFE field `Remarks and Comments` when the underlying "Inspection Report BZ bug' is created.
image

At this point, there is no need to map the BZ mandatory bug description to any visible field in the MEFE interface for Inspection Reports.

Context: Because we need to be able to edit the 'Remarks and Comments' field, the 'Remarks and Comments' field in the MEFE should always display the content of the BZ field `status_whiteboard` from the BZ table `bugs`

# for L 406 - `details` 
@nbiton the text in `details` (L406) is generate from this screen right?

image

If this is the case then this should be mapped to 
- the BZ field `status_whiteboard` in the BZ table `bugs`
- The field 'Remarks and comments' in the PDF export.

# General comment:

We should ideally rename this `description` to something else to be as consistent as possible in the back-end and avoid the confusion between:
- status_whiteboard
- Remarks and Comments
- Details
- Description

maybe we can use `bz_bug_description` for `description`?

**Comment by nbiton** [comment]
It's fully ready now. @franck-boullier feel free to merge when you see fit

**Pull request merged**
