### PR TITLE
Email verification

### PR DESCRIPTION
**Pull request by kaihendry**
TODO:

* https://github.com/unee-t/frontend/issues/407

### CODE REVIEW

**Comment by franck-boullier** [comment]
@kaihendry how can I test this?

**Comment by nbiton** [comment]
@franck-boullier create a new user using the sign up form (with a valid email address)

**Comment by franck-boullier** [comment]
# The Test:
- Create a new user (with a valid email address)
## Expected result:
- User account is created PASSED
- An email with an email verification link is received on the email address used to create the account FAILED
## Actual result
- After 10mn, no email received

**Comment by franck-boullier** [comment]
forget it... I tested on the PR an not on the DEV (my bad) re doing the test now 😊

**Comment by franck-boullier** [comment]
# The Test:
- Create a new user (with a valid email address)
## Expected result:
- User account is created PASSED
- An email with an email verification link is received on the email address used to create the account PASSED
- click on the link on the email ---> go to Unee-T PASSED
- check that the email for this user has been marked as verified / true in the mongo DB PASSED

All works as intended

**Pull request merged**
