### PR TITLE
Comment attachments

### PR DESCRIPTION
**Pull request by nbiton**
Includes:

- Uploading and preview UI
- File uploading to Cloudinary
- "Attachment comment" creation
- Attachment rendering in message list
- Maximized attachment view on click
- Handling of failed uploads
- Error presentation and retry button for failed uploads
- Using cloudinary API to load responsive computed-sized thumbs to save bandwidth

### CODE REVIEW

**Comment by nbiton** [comment]
New stuff added:
- Handling of failed uploads
- Error presentation and retry button for failed uploads
- Using cloudinary API to load responsive computed-sized thumbs to save bandwidth

**Comment by franck-boullier** [comment]
tested on FBO mobile (galaxy S8) and Desktop (FF 57.02 64bits)
All work as intended

**Comment by nbiton** [comment]
It's ready from the functionality aspect. I'm going to add a few basic tests before merging. There will be a need to follow with more comprehensive tests later

**Comment by nbiton** [comment]
Made a few small tweaks and fixes, and added tests for the first epics.
Any review or feedback is welcome :smile:

**Comment by franck-boullier** [comment]
I'll review the PR right now :-P

**Comment by franck-boullier** [comment]
Test done
from a mobile the picture is taken all right
Upload is done OK (and fast)

Issue: when trying to display the picture, the pic takes a long time to download (much slower than before).
 @nbiton, are we adjusting optimizing the picture for upload download or are we saving the picture in full resolution (which might explain the download time)?

**Comment by franck-boullier** [comment]
hitting the back button on the mobile brings back to the case: this is good!

**Comment by nbiton** [comment]
@franck-boullier One of more recent changes was to use the transformations feature on Cloudinary to load responsive computed thumbnails for image attachments for viewing them on the comment list. Before, it was loading the original image for each comment. Now, only when switching over to the maximized view it loads the full image. It appears to take longer to view a maximized image as before it loaded from cache. Overall, the current implementation is a much better approach as the loading time of the entire list is greatly reduced when dealing with a few attachments.

About the back button functionality - this is a part of a refactoring of the case component to multiple sub-routes so it would be possible to integrate the case's additional info view.

**Comment by nbiton** [comment]
There are some CI issues issues to the test runner which is running PhantomJS which is incompatible with some core browser APIs. I'll figure out a way to work around it before merging

**Pull request merged**
