### PR TITLE
Remove user from unit

### PR DESCRIPTION
**Pull request by nbiton**
Addresses issue #194

### CODE REVIEW

**Comment by nbiton** [comment]
How best to test this on the review app (currently):
1. Create a dummy inspection report on the unit of choice.
2. Go to the "sign report" view.
3. Invite a user to sign report.
4. Leave without signing and go to the unit overview tab.
5. Remove the invited user with the X button

**Comment by nbiton** [comment]
New UI implemented:
screenshot from 2019-02-14 11-06-17
screenshot from 2019-02-14 11-06-29
screenshot from 2019-02-14 11-08-16
screenshot from 2019-02-14 11-06-51

**Comment by franck-boullier** [comment]
# The test:

- log is a Leonel - PASSED
- create a new unit - PASSED
- create a new case in this unit - PASSED
- Invite another user (marley) to this case  - PASSED
- Go to the 'Unit' page - try to remove user Marley from the role in the unit - FAILED

## Expected result: 

- There is a way to remove Marley from his current role in the unit

## Actual result:

- No option to remove Marley from his role in the unit.

@nbiton what am I missing?

**Comment by nbiton** [comment]
Performed the following test:

- Created a new user A - PASSED.
- Created a new unit - PASSED.
- Created a new draft report - PASSED.
- Proceeded to report preview - PASSED.
- Proceeded to signing a report - PASSED.
- Invited a new user B to sign the report - PASSED. (Case invitations don't work on review apps)
- Navigate to unit overview and see new user B listed under 'PEOPLE' with 'X' button next to it - PASSED.
- Click the 'X' button to show the confirmation dialog - PASSED.
- Confirm the removal action - PASSED.

After this action, new user B was successfully removed from the unit, and no longer appeared under 'PEOPLE'

**Comment by franck-boullier** [comment]
I was testing in the DEV/Staging instead of the PR App... 😊 

Now I'm trying to test in the PR App but the user I usually choose for test for PR apps (leonel@mailinator.com) is not able to log in (endless loading page).

@nbiton are all the old users gone in the PR apps?

**Comment by nbiton** [comment]
No... any users in specific you'd like me to remove/reset? (Along with leonel@mailinator.com)

**Comment by franck-boullier** [comment]
@nbiton: I can't see the 'X' button (Firefox on a Desktop)

image

**Comment by nbiton** [comment]
@franck-boullier Please let me know which user you were logged in as

**Comment by franck-boullier** [comment]
@nbiton 
Logged in as leonel.
Issue is there for FF on desktop and also for chrome on android.
Symptom is the same: the 'X' is not visible...

**Comment by nbiton** [comment]
@franck-boullier the "source of truth" for unit meta data is Mongo. Although "Leonel" is the creator of unit 1256, it was created in "dev" and therefore never recorded in the PR apps Mongo instance.
The "ownerIds" field stored in the unitMetaData for each unit is used to check whether the current user is allowed to remove any users from the unit, but since 1256 has no unitMetaData recorded, MEFE detects Leonel as a non-owner of the unit and hides the "x" buttons next to other user's names

**Comment by franck-boullier** [comment]
merging to be able to do further testing with invitations.

**Pull request merged**
