### PR TITLE
Dialogs to edit solution and next steps and deadline dates

### LINKED ISSUE #853: Creating next steps, next step date&time, solution and deadline
# Context
Before implementing the nested view for cases, next steps, next steps date&time, solution and deadline have to be created so that we will have a calendar view of the open cases. 
 
Screenshot 2019-07-17 at 1 48 56 PM

Designs are in [figma](https://www.figma.com/file/SgLcXdmBih1JxVq1lupMiPtr/Unee-T-Designs?node-id=0%3A6746)

Point to note: Deadline does not have a time element to it.

### PR DESCRIPTION
**Pull request by nbiton**
Resolves #853

There are two limitations that keep this PR from being implemented exactly like the design sketches. The first is that the hours and minutes display and editing is disabled for "Next Steps Deadline" as the BZ API is blocking setting a datetime to that field. That will need to be resolved with a configuration/schema change on the BZ side, and then it could be re-enabled on the UI.

The second is that the bottom drawer menu that opens after clicking an icon in the top right corner is not available with the version of the UI library we're currently using. It is available with the newest version of the library, but an upgrade requires a migration which is quite non-trivial.

Screenshot from 2019-08-14 19-14-30
Screenshot from 2019-08-14 19-10-25
Screenshot from 2019-08-14 19-10-41
Screenshot from 2019-08-14 19-10-59
Screenshot from 2019-08-14 19-11-21
Screenshot from 2019-08-14 19-11-31
Screenshot from 2019-08-14 19-12-04
Screenshot from 2019-08-14 19-12-25

### CODE REVIEW

**Comment by franck-boullier** [comment]
Tests done in the heroku App on a Samsung Galaxy S8 on chrome
Logged in as Nath
go to case 75810

# Edit Solution:

- Click on the edit icon
- Modal window appears - PASSED
- Add some text for the `solution`: the title texts for each area are overlapping making it difficult to read. Also it's only possible to see 2 lines of text <-- impossible to see what I'm typing as the Solution.
- Add a deadline
- Calendar appears - PASSED
- Save 

## Expected result:

The New Solution and Solutoin dates are visible

## Actual Result:

- The a text "deadline" with a date is briefly visible and then disappears
- The new text for the solution is not visible. We can only see the old text.
- Refresh the page
- Deadline is not visible.

# Edit Next Step:

- Click on the edit icon
- Modal window appears - PASSED
- Add some text for the `Next step`: the title texts for each area are overlapping making it difficult to read
- Add a Next Step
- Calendar appears - PASSED
- Pick a date - PASSED
- Save - PASSED

## Expected result:

The New Next Step and Next Step dates are visible

## Actual Result:

This does NOT work as expected

- A text with "deadline" (instead of "Next Step") is briefly visible and then disappears
- The new text for the Next Step is not visible. We can only see the old text.
- Refresh the page
- Deadline is not visible.

**Comment by nbiton** [comment]
The BZ API request to update the solution or the next steps results in the following error:
```
"API error : [DBD::mysql::st execute failed: Lambda API returned error: Invalid Request Content. Could not parse request body into json: Illegal unquoted character ((CTRL-CHAR, code 10)): has to be escaped using backslash to be included in string value
 at [Source: (byte[])"{"plb64":"eyJjYXNlX2lkIjogNzU4NTAsICJ1bml0X2lkIjogMTI0MSwgInVzZXJfaWQiOiA2LCAibmV3X3Zh
bHVlIjogIlRlc3QgMSIsICJvbGRfdmFsdWUiOiAiIiwgImNhc2VfdGl0bGUiOiAidGVzdCBjYXNl
IGluIHRoZSBERVYvU3RhZ2luZyIsICJ1cGRhdGVfd2hhdCI6ICJTb2x1dGlvbiIsICJjdXJyZW50
X3N0YXR1cyI6ICJDT05GSVJNRUQiLCAiYnpfc291 [for Statement "INSERT INTO bugs_activity
        (bug_id, who, bug_when, fieldid, removed, added, comment_id, attach_id)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?)" with ParamValues: 0=75850, 1=6, 2='2019-08-14 17:34:44', 3=64, 4='', 5='Test 1', 6=undef, 7=undef] at /opt/bugzilla/Bugzilla/Bug.pm line 4451.
	Bugzilla::Bug::LogActivityEntry(75850, "cf_ipi_clust_1_solution", "", "Test 1", 6, "2019-08-14 17:34:44") called at /opt/bugzilla/Bugzilla/Bug.pm line 1141
	Bugzilla::Bug::update(Bugzilla::Bug=HASH(0x55e54a9f29f0)) called at /opt/bugzilla/Bugzilla/WebService/Bug.pm line 681
	Bugzilla::WebService::Bug::update(Bugzilla::WebService::Server::REST::Bugzilla::WebService::Bug=HASH(0x55e54aaf4758), HASH(0x55e54ab43150)) called at (eval 1076) line 1
	eval ' $procedure->{code}->($self, $params) ' called at /usr/local/share/perl/5.26.1/JSON/RPC/Legacy/Server.pm line 208
	JSON::RPC::Legacy::Server::_handle(Bugzilla::WebService::Server::REST::Bugzilla::WebService::Bug=HASH(0x55e54aaf4758), HASH(0x55e54aaa8fa8)) called at /opt/bugzilla/Bugzilla/WebService/Server/JSONRPC.pm line 282
	Bugzilla::WebService::Server::JSONRPC::_handle(Bugzilla::WebService::Server::REST::Bugzilla::WebService::Bug=HASH(0x55e54aaf4758), HASH(0x55e54aaa8fa8)) called at /opt/bugzilla/Bugzilla/WebService/Server/REST.pm line 98
	Bugzilla::WebService::Server::REST::handle(Bugzilla::WebService::Server::REST::Bugzilla::WebService::Bug=HASH(0x55e54aaf4758)) called at /opt/bugzilla/rest.cgi line 30
	ModPerl::ROOT::Bugzilla::ModPerl::ResponseHandler::opt_bugzilla_rest_2ecgi::handler(Apache2::RequestRec=SCALAR(0x55e54aaf1098)) called at /usr/lib/x86_64-linux-gnu/perl5/5.26/ModPerl/RegistryCooker.pm line 207
	eval {...} called at /usr/lib/x86_64-linux-gnu/perl5/5.26/ModPerl/RegistryCooker.pm line 207
	ModPerl::RegistryCooker::run(Bugzilla::ModPerl::ResponseHandler=HASH(0x55e54aa8b2a8)) called at /usr/lib/x86_64-linux-gnu/perl5/5.26/ModPerl/RegistryCooker.pm line 173
	ModPerl::RegistryCooker::default_handler(Bugzilla::ModPerl::ResponseHandler=HASH(0x55e54aa8b2a8)) called at /usr/lib/x86_64-linux-gnu/perl5/5.26/ModPerl/Registry.pm line 32
	ModPerl::Registry::handler("Bugzilla::ModPerl::ResponseHandler", Apache2::RequestRec=SCALAR(0x55e54aaf1098)) called at /opt/bugzilla/mod_perl.pl line 140
	Bugzilla::ModPerl::ResponseHandler::handler("Bugzilla::ModPerl::ResponseHandler", Apache2::RequestRec=SCALAR(0x55e54aaf1098)) called at (eval 1076) line 0
	eval {...} called at (eval 1076) line 0
]"
```
This is the cause for the symptom of the text reverting back to its previous state.
@kaihendry any ideas why this is happening?

**Comment by nbiton** [comment]
The testing code on the lambdas on DEV has been reverted by @kaihendry . It seems to have fixed the issue. Please test again.

**Comment by nbiton** [comment]
The latest commit should fully fix the layout issue

**Pull request merged**
