### PR TITLE
feat: adjusted UI to fit the design changes requested in #199

### PR DESCRIPTION
**Pull request by nbiton**

### CODE REVIEW

**Comment by franck-boullier** [comment]
On Galaxy s8 with Chrome, after login credentials for Lionel are entered then page is loading forever and is not displayed

**Comment by franck-boullier** [comment]
This seem to be related to the expiration issue 
image

This seems to be linked to Issue #178

**Comment by franck-boullier** [comment]
There are apparently no user I can use to test on the Heroku deployment unfortunately: all seem to have expired tokens...

**Comment by franck-boullier** [comment]
I'm able to connect now!

# The test:
Go to a case
invite an existing user

# Expected result:
See a list of user who have NOT been invited yet FAILED 

# Actual result:
1- We see the list of all the users: invited and not invited
2- When one click on the invitation 'tick', it seems to invite the user immediately. 
3- The 'invite user' button doesn't seem to do anything.
image

# Misc remarks:
The new flow should separate 'invite' from 'remove' user.
Remove should be a 'x' next to the currently invited user. Click on the 'x' opens a confirmation window to confirm that the user(s) will be 'Uninvited'
Invite should be done via the 'invitation' link below the list of users.
Invite/remove user is still done on the same window. (After user click on 'Invite or remove user')
image

**Comment by franck-boullier** [comment]
# The test:
Check the the 'search user' box has been removed: PASSED

**Comment by franck-boullier** [comment]
#The Test:
Check that the 'assign user' interface has been updated according to the new design: PASSED

**Comment by nbiton** [comment]
All changes are already included in #218 , so this one would be closed without merging

**Pull request closed without merging**
