### PR TITLE
Fetch user cases API

### PR DESCRIPTION
**Pull request by nbiton**
This is a WIP solution for #51

### CODE REVIEW

**Comment by franck-boullier** [comment]
Just tested the Heroku side of this and I am still not able to access a case (but I can log in)
I have an ever loading page again...

**Comment by franck-boullier** [comment]
latest version of this PR still does not work as intended: I cannot access any case: I have an ever loading page again

http://unee-t-pr-53.herokuapp.com/case/12345

**Comment by franck-boullier** [comment]
I added a screen capture of the issue in the issue #55 as I believe this might be the root cause of the issue of the ever loading page.

**Comment by kaihendry** [comment]
Oh if public.CLOUDINARY_URL is undefined, then it's almost certainly related to https://github.com/unee-t/frontend/issues/55

**Comment by nbiton** [comment]
It was caused by an issue in the Heroku deployment :sweat_smile: I fixed it manually.
It wasn't related to #55

**Comment by franck-boullier** [comment]
I am able to log in and access cases now.
New features:
- See the Next Steps and solution in the main case screen
- See all the pictures takes in the media section of the 'more info' screen for the case

All works as intended for these 2 features, unless anyone objects to that I'm happy to merge it in master as this fixes a few issues already.

@nbiton maybe we can rename this PR and create a different one to address issue #51?

**Comment by nbiton** [comment]
@franck-boullier These two features were already included in #41 , but since it was already merged to master before it was tested, and our dev environment was down, it went unnoticed. The content of this PR actually matches the title :grin:

**Comment by nbiton** [comment]
Tested on https://unee-t-pr-53.herokuapp.com and works as designed. Planning to merge soon.

**Comment by franck-boullier** [comment]
I confirm that I can retrieve the list of open cases when I log
All works as intended as far as I'm concerned

**Pull request merged**
