### PR TITLE
Enhanced notification filtering options

### LINKED ISSUE #714: Update the Notification Whitelist
# Context:

The current notification engine sends notification when cases are updated.
As part of the payload we have a `updated_what` field that describes what is the field that was changed.
Notification events happen for any type of changes in Unee-T, regardless of the front end used.
The BZFE and the MEFE are different. BSFE displays much more information than the MEFE.
In order to minimize noise we have implemented a Whitelist mechanism for the MEFE users: the notifications are passed on to the MEFE user if the `updated_what` field is recognized in the Whitelist.

# Current Whitelist:

Notifications are considered as valid for the 'case_updated' trigger if the `updated_what` is one of the following values:
- 'Unit',
- 'Role',
- 'Component',
- 'Product',
- 'Severity',
- 'Priority',
- 'Platform',
- 'Case Category',
- 'Summary',
- 'Next Step',
- 'AssignedTo',
- 'Resolution',
- 'Solution',
- 'Status',
- 'CC'

# The problem:

The current whitelist need to be reviewed to make sure we are sending sensible notifications to the users.

The Fields that are currently visible in the MEFE interface are:

- category: 'rep_platform', (Case Category)
- subCategory: 'cf_ipi_clust_6_claim_type', (Case Type)
- priority: 'priority', (Priority)
- severity: 'bug_severity', (Severity)
- selectedUnit: 'product', (Unit)
- assignedUnitRole: 'component', (Role)
- title: 'summary', ()
- details: 'description', ()
- nextSteps: 'cf_ipi_clust_1_next_step', (Next Step)
- nextStepsBy: 'cf_ipi_clust_1_next_step_by', (Next Step Date)
- solution: 'cf_ipi_clust_1_solution', (Solution)
- solutionDeadline: 'deadline', (Deadline)
- involvedList: 'cc', (CC)
- involvedListDetail: 'cc_detail', ()
- assignee: 'assigned_to', ()
- assigneeDetail: 'assigned_to_detail', ()
- creator: 'creator', ()
- creatorDetail: 'creator_detail', ()
- status: 'status', (Status)
- resolution: 'resolution', (Resolution)
- additionalComments: 'whiteboard' (Status Whiteboard)

# The udated White List:

Updated white list should be:
- status: 'status', (Status)
- severity: 'bug_severity', (Severity)
- selectedUnit: 'product', (Unit)
- assignedUnitRole: 'component', (Role)
- nextSteps: 'cf_ipi_clust_1_next_step', (Next Step)
- nextStepsBy: 'cf_ipi_clust_1_next_step_by', (Next Step Date)
- solution: 'cf_ipi_clust_1_solution', (Solution)
- solutionDeadline: 'deadline', (Deadline)

### PR DESCRIPTION
**Pull request by nbiton**
This PR addresses issue #331 and fixes #714.

### Current Implementation
Out of issue #331, this PR currently handles:
- Overriding definition of the user's global notification settings on the case or unit level.
- Cascade logic to allow overriding on a case level what's defined on the unit level (additional future levels could be added with the same logic). This logic allows overriding just the sub type on any level as well (increased available filtering granularity).
- Implementation for new filtering notification sub types:
  - For "caseUpdate":
    - Notification payload with "updated_what" value of "Deadline"
    - Notification payload with "updated_what" value of "Solution"
  - For "caseNewMessage":
    - Notification payload that originated from a user of role "Tenant"
    - Notification payload that originated from a user of role "Owner/Landlord"
    - Notification payload that originated from a user of role "Contractor"
    - Notification payload that originated from a user of role "Management Company"
    - Notification payload that originated from a user of role "Agent"

### Implementation in progress (in the scope of this PR)
The following items are yet to be implemented:
- Filtering by "caseUpdate" type notifications when the status changed to resolved. Impediment: the notification message payload does not contain the status, but only contains 'updated_what: Status' to let MEFE know the case's status has changed.
- Overriding other filtering overrides when the case's "severity" is equal above a set level. Impediment: More complicated logic; Need to define the severity scale.

### Schema changes
To implement this feature, the following changes were made to the Mongo schema:
- In the user's collection, the following items were added to the "notificationSettings" object:
  - "caseUpdate_types" - an object with the following keys:
    - "Solution" (boolean)
    - "Deadline" (boolean)
    - "StatusResolved" (boolean)
  - "caseNewMessage_types"- an object with the following keys:
    - "Tenant" (boolean)
    - "Owner/Landlord" (boolean)
    - "Contractor" (boolean)
    - "Management Company" (boolean)
    - "Agent" (boolean)
  - "severityOverrideThreshold"- an enum string with a default value of null (which means it's unset). Should correspond to the available case "severity" enum values.
- An automated migration is included in this PR to add all the above changes to existing users.
- An empty collection named "notificationSettingsOverrides" was added. This collection will have a document for each user+unit/case combination that includes an override of the global/higher level settings. These documents need to be created manually by us (as admins) in Mongo until we have a UI to manage it automatically. Each document in this collection is of the following format:
```
{
   userBzId: int,
   caseId/unitBzId: int,
   settings: { // Partial or complete definition of the following: (same as global notificationSettings on the user doc)
    assignedNewCase: boolean,
    assignedExistingCase: boolean,
    invitedToCase: boolean,
    caseNewMessage: boolean,
    caseUpdate: boolean,
    caseUpdate_types: {
      'Solution': boolean,
      'Deadline': boolean,
      'StatusResolved': boolean
    },
    caseNewMessage_types: {
      'Tenant': boolean,
      'Owner/Landlord': boolean,
      'Contractor': boolean,
      'Management Company': boolean,
      'Agent': boolean
    },
    severityOverrideThreshold: string/null
  }
}
```

### Testing method
The PR review app can be tested by triggering mock message payloads with Postman.
Please copy the saved request "Local"->"Trigger notification handler on localhost" and change according to your testing parameters.
screenshot from 2019-02-21 09-14-25
For the scope of the test:
- "case_id" does not need to correspond to an actual case.
- "unit_id" **does need** to correspond to an actual unit bz id. (so its roles can be resolved)
- "user_id", "case_reporter_user_id", "old_case_assignee_user_id", "new_case_assignee_user_id", "current_list_of_invitees" **all need to correspond** with actual user BZ ids already recorded as MEFE users in Mongo.
- To test the "caseNewMessage" sub types, change the "user_id" attribute to one of the matching role in the specified unit.

### CODE REVIEW

**Comment by nbiton** [comment]
@franck-boullier is it possible to add the severity of the case to the message payload as well?
I need it to determine if the severity override applies over other filters

**Comment by franck-boullier** [comment]
@nbiton looking at this now to prep for the 14h00 demo 😅

**Comment by nbiton** [comment]
These functionalities were implemented following the completion of https://github.com/unee-t/bz-database/issues/115 :
- Filtering by "caseUpdate" type notifications when the status changed to resolved. Also, status updates that **don't** signal the case has been resolved, are filtered always for all users (they seem irrelevant, and the setting won't have any meaning otherwise).
- Overriding other filtering overrides when the case's "severity" is equal to, or above a certain level.

This PR is finalized and ready to be verified and merged to master.
@franck-boullier feel free to check it and merge whenever you prefer.

**Comment by nbiton** [comment]
@kaihendry please feel free to merge this PR

**Comment by nbiton** [comment]
@franck-boullier can I merge this?

**Comment by franck-boullier** [comment]
> can I merge this?

Yes please

**Pull request merged**
