### PR TITLE
Unit floor plan upload

### PR DESCRIPTION
**Pull request by nbiton**
Takes care  of a portion of issue #855 

image
image
image
image

### CODE REVIEW

**Comment by franck-boullier** [comment]
Test went OK

# Minor Issue 1:

@nbiton I noticed that the user has to click on the "Edit" icon to be allowed to upload a floor plan.
Can we skip this step <--- no need to click on the "Edit" icon if there is no floor plan for that unit?

# Minor issue #2: 

The "Edit" icon switches from 
image
to 
image

This is confusing.
Can we use a "Tick" icon instead of an "x" icon?

# Minor Issue #3:

The order of the blocks is
- Address
- Floor Plan

image

Can we switch the order to
- Floor Plan
- Address

# Minor Issue #4:

The format of the Text "Floor plan" 
image
is not consistent with the format of the text "Address"
image
Can we standardize this and make sure that the text format for "Floor Plan" is changed to the formart we are currently using for the text "Address"

**Comment by franck-boullier** [comment]
# Major Issue:

I'm not able to add a floor plan to some unit: The "Edit" icon is not visible.

## How to reproduce the issue:

On the Heroku App
Log in as nath
go to [unit 944](http://unee-t-pr-871.herokuapp.com/unit/944/overview).
There is no way to add a floor plan
image

**Comment by nbiton** [comment]
The edit icon is visible only if you're the owner of the unit. That's also the reason the upload is made available after clicking the edit button

**Comment by franck-boullier** [comment]
> The edit icon is visible only if you're the owner of the unit. That's also the reason the upload is made available after clicking the edit button

This should NOT work like this.
We want to make it very simple for user to add a floor plan to the unit.
Even if the user is NOT the owner of the unit, if the user has access to the unit, then the user should be allowed to upload a floor plan.

**Comment by nbiton** [comment]
@franck-boullier What about changing or removing the floor plan?

**Comment by franck-boullier** [comment]
# Minor issue #2 - clarification: 

The "Edit" icon switches from 
image
to 
image

This is confusing <--- why is this confusing? Because I don't see a "Save" button that I can press once I've made the change to the unit information.

Can we use a "Tick" icon somewhere (Save)?
Today, because we have an "x" icon I understand how we can cancel but because we are missing a "Save" icon I don't understand how I can save my changes.

**Comment by nbiton** [comment]
> Because I don't see a "Save" button that I can press 

The "Save" button is in the top right of the screen. It has been discussed before (when Liron was working on it), but still remained that way.
Before we make any changes to the design, I think it would be best to have @ongdominick and @kiatlim involved

**Comment by franck-boullier** [comment]
> The "Save" button is in the top right of the screen.

OK I just noticed it <--- it was totally invisible for me and I only saw it when @nbiton specifically reminded me that the save button was there.

We definitely need to put the "Save" button where all the other "Save" buttons are <--- usually docked at the bottom of the screen (if memory serves)

@ongdominic I'll let you update the design with your recommended improvement

**Comment by franck-boullier** [comment]
Fixed in the latest version of the PR: anyone can add a floor plan to a unit

**Comment by ongdominic** [comment]
Here is the design for this issue. Details are in [figma](https://www.figma.com/file/SgLcXdmBih1JxVq1lupMiPtr/Unee-T-Designs?node-id=3665%3A5662)
Screenshot 2019-09-02 at 4 22 45 PM

Important note: the footer with the save and cancel button is sticky at the bottom of the screen

**Comment by nbiton** [comment]
I implemented the new design for "save" and "cancel" and rearranged the floor plan "card" to be second in row

**Pull request merged**
