### PR TITLE
feat: case floor plan pins editing

### PR DESCRIPTION
**Pull request by nbiton**
Takes care of the pins editing portion of #855 

image
image
image
image

### CODE REVIEW

**Comment by franck-boullier** [comment]
feat: allow to add floor plan pins to a case after creation <-- Tested. This works as intended.

**Comment by nbiton** [comment]
The remainder of #855  is implemented now. @franck-boullier please review

**Comment by franck-boullier** [comment]
@nbiton it seems that the deployment did not work as expected. Can you confirm that I can test on Heroku now?

**Comment by nbiton** [comment]
I just made it redeploy. You can try again in a few minutes

**Comment by franck-boullier** [comment]
merge to test on the DEV/Staging

**Pull request merged**
