### PR TITLE
MEFE internal API, 3rd installment

### PR DESCRIPTION
**Pull request by nbiton**
Includes:
- Role assignment API. Example request payload: 
```
{
	"actionType": "ASSIGN_ROLE",
	"requestorUserId": "R4vBD6BZRCNx8JwnM",
	"addedUserId": "chFmfTz34ahKcSNM9",
	"unitId": "ths88NatbylBl6dPQ",
	"roleType": "Tenant",
	"isOccupant": false,
	"isVisible": false,
	"isDefaultInvited": true,
	"roleVisibility": {
		"Agent": false,
		"Tenant": true,
		"Owner/Landlord": false,
		"Management Company": false,
		"Contractor": true,
		"Occupant": true
	}
}
```
Example response:
```
{
    "timestamp": "2019-03-21T04:53:54.286Z"
}
```
- Modifications to the unit and user creation APIs- better error handling and inclusion of "isCreator" in the user creation API response

### CODE REVIEW

**Comment by nbiton** [comment]
The corresponding saved example request on Postman is "Assign a role to user in a unit"

**Comment by nbiton** [comment]
Note: although the new role assignment API persists the settings for role visibility, these new role visibility rules are NOT yet implemented

**Comment by franck-boullier** [comment]
@nbiton I have created the SQL trigger that are firing the lambdas to activate the API.

My payload was 
```
{"unitId": "00V9XSzfATFa1DuT1", "roleType": "tenant", "isVisible": "false", "actionType": "ASSIGN_ROLE", "isOccupant": "true", "addedUserId": "RbpcfLvTg26P8phEA", "roleVisibility": {"Agent": "true", "Tenant": "true", "Occupant": "true", "Contractor": "true", "Owner/Landlord": "true", "Management Company": "true"}, "requestorUserId": "YYeAutqzDY3MeqbNC", "isDefaultInvited": "false", "mefeAPIRequestId": 1}
```

How can I check that all went as intended in the MEFE and BZFE?

**Comment by kaihendry** [comment]
Test in Postman? https://media.dev.unee-t.com/2019-03-24/postman.mp4

**Pull request merged**
