### PR TITLE
enhanced case API for 3rd party case viewers/editors

### PR DESCRIPTION
**Pull request by nbiton**

### CODE REVIEW

**Comment by nbiton** [comment]
This PR now includes:
- Individual case retrieval API "GET /api/cases/:id" with comments which returns the following JSON format:
```
{
  "assignee": {
    "userId": <MEFE User Id>,
    "name": <MEFE user name>,
    "role": <MEFE user role in the relevant unit>
  },
  "reporter": {
    "userId": <MEFE User Id>,
    "name": <MEFE user name>,
    "role": <MEFE user role in the relevant unit>
  },
  "caseId": <BZ case Id (int)>,
  "involvedList": <array of people involved in the case (CC) of format similar to the one above>,
  "userRelevance": <array which contains one or more of the following: "Assignee", "Reporter", "Invited To">,
  "creationTime": <ISO format datetime (string)>,
  "title": string,
  "nextSteps": string,
  "solution": string,
  "solutionDeadline": <Date of YYYY-MM-DD format (string)>,
  "category": string,
  "subCategory": string,
  "unitId": <MEFE unit Id>,
  "unitName": <MEFE unit display name>,
  "comments": <array of objects of the following format: {
    "creator": <Similar to user descriptors shown above>,
    "id": <BZ commen Id (int)>,
    "count": int,
    "time": <of creation, ISO format datetime (string)>,
    "type": <any one of the following: "text", "image", "audio", "floorPlan">,
    "text": <optional, only populated  for type "text">,
    "imageUrl": <optional, only populated for types "image" and "floorPlan">,
    "audioUrl": <optional, only populated for type "audio">,
    "floorPlanId": <optional, only populated for type "floorPlan". Contains the MEFE string id for this floor plan under unit meta data>,
    "pins": <optional, only populated for type "floorPlan". An array which contains array of [float, float] coordinates>
  }>
}
```
This API requires specifying the ID parameter and the user's MEFE API with "apiKey" in query string format.

- Case update API "PUT /api/cases/:id" which accepts a JSON request body that contains one or more of the following attributes:
```
  'title',
  'solution',
  'solutionDeadline',
  'nextSteps',
  'nextStepsBy',
  'status',
  'resolution',
  'category',
  'subCategory',
  'priority',
  'severity'
```
This API requires specifying the id parameter and the user's MEFE API key in the request's body as "apiKey" or in an Authentication header Bearer token.

**Comment by franck-boullier** [comment]
@nbiton does this API allow a new user to be created "on the fly" like we can when we create a new case?

# The Scenario:

3rd party App wants to 
- assign the case to a user.
  OR
- invite a new user to the case.

AND
The user that the 3rd party App wants to assign (or invite) to the case does NOT exist in Unee-T (OR that user exists in Unee-T but has NOT been associated to any role in that unit yet).

Ideally, the API will be able to:
1- create that new user
2- assign that new user to the unit in one of the roles
3- determine if the user is a "private" or "public" user in the given role.
4- Add the user to the case as either the assignee or one of the person who has been invited to the  case.

Can you confirm what will happen in each of these scenario?

Thanks

**Comment by franck-boullier** [comment]
@nbiton a few fields seem to be missing from the GET call:
- `details`
- `nextStepsBy`
- `Severity`
- `Priority`

**Comment by nbiton** [comment]
> @nbiton a few fields seem to be missing from the GET call:
> 
> * `details` 
> * `nextStepsBy`
> * `Severity`
> * `Priority`

These are currently not a part of the response, but can be added

**Comment by nbiton** [comment]
> @nbiton does this API allow a new user to be created "on the fly" like we can when we create a new case?

Currently, no.

> 3- determine if the user is a "private" or "public" user in the given role.
> 4- Add the user to the case as either the assignee or one of the person who has been invited to the case.

How do you suggest we allow that? How should these options be specified by the user?

**Comment by nbiton** [comment]
> @nbiton a few fields seem to be missing from the GET call:
> 
> * `details`
> * `nextStepsBy`
> * `Severity`
> * `Priority`

Fixed

**Comment by nbiton** [comment]
d09f484 includes the comment creation API.
The APIs route is `POST /api/cases/:caseId/comments`.
It receives "text" in the body of the request and apiKey can be sent as a part of the body or in an Authentication header Bearer token.

Example:
```
{
  "text": "This is a test comment created via the new API",
  "apiKey": "xxxxxxxxxxx"
}
```

**Comment by nbiton** [comment]
It can't be tested any further locally or on a review app because of the invite lambda dependency. We can merge to master and start testing on dev

**Pull request merged**
