### PR TITLE
Inspection report phase 1 - functional with cases

### PR DESCRIPTION
**Pull request by nbiton**
More details soon

### CODE REVIEW

**Comment by nbiton** [comment]
Implemented so far:
* Create report button re-enabled
create-report-button

* Create draft report re-enabled
create-draft-report

* Report drafting view shows correct report information (otherwise not completely functional yet)
report-draft-view

* Reports listed under Unit's "Reports" tab
reports-listed

* Reports showing up as "finalized" on the list once their status is changed to "CONFIRMED" (can only be fully tested by using the BZ dashboard currently)
reports-list-finalized

**Comment by franck-boullier** [comment]
# The Test:
- Go to the inspection reports page ---> check that the '+' button to create an IR is there - PASSED
- Click on the '+' button ---> check that we go to the first screen for IR creation - PASSED
- Create an IR ---> check that it's possible to add a name and a description to the IR - PASSED
- Hit the back arrow ---> we go back to the list of IR page - PASSED
- Check that the newly created IR is visible and pending (blue clock icon) - PASSED

So far, so good

**Comment by nbiton** [comment]
New implemented features:
* "Add case" button in report draft leads to "Create case" with "Report" context
create-case-report-context
* Clicking on "Add case" to finalize case creation, **takes the user back to report draft view**
* The report draft view lists all the cases under this report
list-cases-under-report
* Clicking on a case in report draft navigates to that case (default case view)
* Clicking "back" from case view leads back to the report draft view.

**Comment by nbiton** [comment]
I see the problem... when I create new case, I need to update it with the report's id set on the "blocks" field and not on "depends_on".
Aside from that, I'll need to adjust that data is read accordingly.

**Comment by nbiton** [comment]
See the commit comments for a description of the latest changes

**Comment by nbiton** [comment]
See the commit comments for a description of the latest changes

**Comment by franck-boullier** [comment]
# The tests:

- Check that we can see the number of IR in the Unit Tab - PASSED
- Go to the inspection reports page ---> check that the '+' button to create an IR is there - PASSED
- Click on the '+' button ---> check that we go to the first screen for IR creation - PASSED
- Create an IR ---> check that it's possible to add a name and a description to the IR - PASSED
- Add a case to that IR:
  - Check that the IR is displayed as we create the case PASSED
  - After case is created check that we go back to the IR PASSED
- Add a second case to that IR:
  - Check that the IR is displayed as we create the case PASSED
  - After case is created check that we go back to the IR PASSED
- Go back to the list of IR and Check that the newly created IR is visible and pending (blue clock icon) - PASSED
- Check that the number of IR in the Unit Tab has increased - PASSED
- Reopen the IR
- Add a third case to that IR:
  - Check that the IR is displayed as we create the case PASSED
  - Check that we can see the number of IR in the Unit Tab - PASSED
  - After case is created check that we go back to the IR - PASSED
- Check that the cases are visible in the 'Case'  view - PASSED
- Go to the BZFE (dashboard)
  - Check that the bug/case for the IR has the `inspection_report` keyword: - PASSED
  - Check that the IR has 3 cases/bugs listed in the 'depends on' field - PASSED
- In the MEFE mark the IR as complete
  - Check that the tick bock changed in the MEFE - PASSED
  - Check that the status changes in the BZFE - PASSED

# Minor UI Issue/ potential user confusion:

Once the report is complete, there is a possible confusion for the user: the 'Complete' button is still active despite the message that said that this is not possible to change the IR anymore.

image

We should: 
- Deactivate or hide the 'Complete' button.
- (Once ready) add the 'Duplicate Report' button to this page

**Comment by nbiton** [comment]
> Once the report is complete, there is a possible confusion for the user: the 'Complete' button is still active despite the message that said that this is not possible to change the IR anymore.

The pushed commit I made minutes ago addresses that issue so there should be no loose ends in this PR and it can be merged as a feature.
The changes are:
* The finalized reports go into "review" mode when they are clicked on from the unit's report listing. It is the same as "draft", but it doesn't allow the user to add any more cases (the instruction changes too) and the confirmation button is replaced by some text.
report-review-mode
* The "review" and "draft" report viewing modes are reflected in the url.
* The report view mode is "enforced" - a user trying to access a finalized report with "draft" mode will be automatically redirected to "review" and vice-versa.

We can decide later if we want to keep "review" existing alongside the pdf export once we have it implemented, or just have the pdf export take its place entirely.

**Comment by franck-boullier** [comment]
# The tests:

- Check that we can see the number of IR in the Unit Tab - PASSED
- Go to the inspection reports page ---> check that the '+' button to create an IR is there - PASSED
- Click on the '+' button ---> check that we go to the first screen for IR creation - PASSED
- Create an IR ---> check that it's possible to add a name and a description to the IR - PASSED
- Add a case to that IR:
  - Check that the IR is displayed as we create the case PASSED
  - After case is created check that we go back to the IR PASSED
- Add a second case to that IR:
  - Check that the IR is displayed as we create the case PASSED
  - After case is created check that we go back to the IR PASSED
- Go back to the list of IR and Check that the newly created IR is visible and pending (blue clock icon) - PASSED
- Check that the number of IR in the Unit Tab has increased - PASSED
- Reopen the IR
- Add a third case to that IR:
  - Check that the IR is displayed as we create the case PASSED
  - Check that we can see the number of IR in the Unit Tab - PASSED
  - After case is created check that we go back to the IR - PASSED
- Check that the cases are visible in the 'Case'  view - PASSED
- Go to the BZFE (dashboard)
  - Check that the bug/case for the IR has the `inspection_report` keyword: - PASSED
  - Check that the IR has 3 cases/bugs listed in the 'depends on' field - PASSED
- In the MEFE mark the IR as complete
  - Check that the tick bock changed in the MEFE - PASSED
  - Check that the status changes in the BZFE - PASSED
- After the IR is completed
  - Check that the 'Complete' button is NOT accessible and replaced with 'Report is finalized' prompt - PASSED

# Minor UI Issue:
## Issue 1
The 'Complete' button should be 'Docked' (always visible) at the bottom of the screen
Current display makes it hard to find if user does not know what to do
image

## Issue 2:

The 'Export' button is not working ---> we should hide it
image

## Issue 3:

Make sure that the 'Report is Finalized' Prompt is 'Docked' (always visible) at the bottom of the screen too: this might be hidden on smaller screens

image

Once this is fixed, OK to merge and release as a new functionality! 🎉

**Comment by nbiton** [comment]
The 3 mentioned issues are fixed, and in addition (as I didn't like how the "docked" bottom section looked), I  implemented a subtle scroll shadow effect that indicates to the user that there is more content when scrolling down, but blends to be unnoticeable when the container is scrolled all the way down.
screenshot from 2018-08-07 16-56-43
screenshot from 2018-08-07 16-57-03

**Pull request merged**
