### PR TITLE
feat: temporarily disabled the welcome dialog for invited users

### PR DESCRIPTION
**Pull request by nbiton**
The welcome dialog will not show up for newly invited users, and they will not be prompted to fill in their first and last name.
The dialog code is just disabled for now and can be reenabled once it is decided how it needs to be adjusted or replaced

### CODE REVIEW

**Comment by nbiton** [comment]
Resolves #564

**Comment by franck-boullier** [comment]
@nbiton any recommendation on how I can test that?

**Comment by franck-boullier** [comment]
@kaihendry once we deploy this we probably need to have Uilicious update some of their automated tests too to avoid false positive right?

**Comment by nbiton** [comment]
> @nbiton any recommendation on how I can test that?

Invitations don't work on PR apps actually, so no :sweat_smile: 

Should I merge to dev?

**Comment by franck-boullier** [comment]
> Should I merge to dev?

Sure let's do this!

**Pull request merged**
