### PR TITLE
More case fields editable

### LINKED ISSUE #831: Enable user to update `Case Category` and `Case Type` of an existing case
# The Problem:

Users have no way to edit the `Case Category` and `Case Type` of an existing case

image

### LINKED ISSUE #832: Enable user to update `Priority` and `Severity` of an existing case
# The Problem:

Users have no way to edit the `Priority` and `Severity` of an existing case

image

### PR DESCRIPTION
**Pull request by nbiton**
Resolves #831
Resolves #832

### CODE REVIEW

**Comment by franck-boullier** [comment]
@nbiton I have an endless loading page when trying to access a case

# How to replicate the Issue:

- Go to the [Heroku App](https://unee-t-pr-851.herokuapp.com).
- Try to access [case 73843](https://unee-t-pr-851.herokuapp.com).

image

**Comment by franck-boullier** [comment]
More information:
After 3mn the page finally loaded.

# Other error - Impossible to change the fields:

How to replicate the issue
- Log in as Nath.
- Go to [case 73843/details](https://unee-t-pr-851.herokuapp.com/case/73843/details)
- Try to change the `case category`
- The `case category` is changed
- After a few seconds the `case category` is reverted back to the initial value: the change is cancelled.
- This is true for all 4 fields: 
  - `Category`, 
  - `Sub-Category` <--- side note: this should be renamed to `Case Type` for consistency with the dashboard 
  - `Priority`
  - `Severity`

**Comment by nbiton** [comment]
@franck-boullier I managed to inch closer to the source of the problem (edit rejected). When we update the bug with BZ API, it responds with a 200 success http code, but contains the following error message:
"'Can\'t locate object method "prepare_cached" via package "Bugzilla::DB::Mysql" at /opt/bugzilla/Bugzilla/Bug.pm line 4431.\n'"

Any idea what is causing this?
(or @kaihendry ?)

**Comment by kaihendry** [comment]
I'm guessing this is from https://dashboard.dev.unee-t.com/? Be good if you could document the erroneous request in Postman and save the response too if possible. 

It could be because of the WIP of https://github.com/bugzilla/bugzilla/pull/79 which is only in dev atm. I guess there is no way to try in demo to be sure?

**Pull request merged**
