### PR TITLE
Case update markers

### PR DESCRIPTION
**Pull request by nbiton**
This PR addresses #337 .
In addition, it also includes messaging app-like unit/case ordering, and individual case update/message counters to signify activity to the user.

The PR does not implement "mark as read" functionality yet (removing "unread" markers from a case once it has been visited).

Instructions on testing this on the PR app will follow soon

### CODE REVIEW

**Comment by nbiton** [comment]
I added a saved request to our Postman account to simulate sending a notification to the app. 
To use this properly: 
* "notification_id" needs to be modified to something unique
* "case_id" has to match the case id
* "unit_id"  has to match the unit's **bz** id
* "notification_type" can be either "case_new_message" or "case_updated" (but if changed to "case_updated" you need to modify the other parts of the body to match the payload the payload format)
* The user's bz id you're testing for has to be mentioned in either "current_list_of_invitees", "new_case_assignee_user_id" or "case_reporter_user_id" (99 is for Leonel)
* "created_by_user_id" has to match any other user which is not your user (100 is Marley)

The other body attributes don't matter for the sake of testing this feature.
screenshot from 2018-07-13 21-38-14

You can have the main "Cases" view open while sending requests to see it updating live.

**Comment by franck-boullier** [comment]
@nbiton it looks great so far!
The mechanism to mark case as read is not implemented yet right?

**Comment by nbiton** [comment]
The mechanism to mark as read is now fully implemented.

This is ready to be tested in full now.

**Comment by franck-boullier** [comment]
# The tests done:

## Test 1 as leonel:
- Login as leonel check if you see notification: PASSED
- go to an updated case add a comment to the case
- go back to the list of cases, check that the case I just viewed is not highlighted anymore PASSED.

## Test 2 as Marley:
- log out and log back in as Marley (a user invited to the case)
- go to the list of cases check that the case that was just updated as Leonel is higlighted in the list of cases PARTIAL PASS.

### Actual result:

The list of units and case seems to be ordered as it should (maybe a coincidence??):
- First unit is the unit updated as Leonel PASSED
- First case for the first unit is the case that was updated PASSED
- The unit with the updated case is higlighted in bold FAILED
- The case is higlighted in bold and the notification icon is displayed FAILED

**Comment by franck-boullier** [comment]
# Further tests:
## Test 1 as leonel:
- Login as leonel check if you see notification: PASSED
- go to an updated case add a comment to the case make sure to select a case which is NOT first in the list
- Invite Marley to the case
- Add another comment to the case
- go back to the list of cases, check that the case I just viewed is not highlighted anymore PASSED.

## Test 2 as Marley:
- log out and log back in as Marley (a user invited to the case)
- Check that the 
- go to the list of cases check that the case that was just updated as Leonel is higlighted in the list of cases FAILED.

### Actual result:

The list of units and case is NOT ordered as it should (it WAS a coincidence in the previous test):
- First unit is the unit updated as Leonel FAILED
- First case for the first unit is the case that was updated FAILED
- The unit with the updated case is higlighted in bold FAILED
- The case is higlighted in bold and the notification icon is displayed FAILED

**Comment by nbiton** [comment]
@franck-boullier Sorry for not making it clear, but you can test ONLY with the method I described above- using Postman to **simulate** notifications.
Adding comments or makings changes to case will not cause notifications to appear, as this is a PR app, and the lambda is not set to call it and post notifications to users.
We could only test the full flow after it is merged and deployed to dev

**Comment by nbiton** [comment]
You actually don't need to update a case or add comments at all. The notifications are completely unrelated to the actual case modifications and rely on the "ses2case" data flow only

**Comment by franck-boullier** [comment]
> We could only test the full end to end flow after it is merged and deployed to dev

Oh! OK I get it, it makes sense...
In that case, I recommend that we do the merge now so we can test in the DEV/Staging right away in a 'Real Life' kinda scenario.

@nbiton do you see any issue with that approach?

**Comment by nbiton** [comment]
One more thing that I think I should highlight is that the way the unit/case ordering works is that the first item on the list is the one that was most recently updated and not the one that has unread notifications (this makes it easier for the user to go over multiple items with unread notifications, then go back and click on another, while the list still keeps its ordering as long no newer notifications were received)

**Comment by franck-boullier** [comment]
> the first item on the list is the one that was most recently updated and not the one that has unread notifications

I agree, this is the correct behavior IMO too

**Comment by nbiton** [comment]
> @nbiton do you see any issue with that approach?

I think a simulated tests should be done first just to make sure it is not completely off-track and getting our master branch unstable so it's blocking other stuff from being pushed to prod.
The saved postman request should make it quite easy to do a simulated test.

**Comment by franck-boullier** [comment]
> I think a simulated tests should be done first just to make sure it is not completely off-track and getting our master branch unstable so it's blocking other stuff from being pushed to prod

OK I see your point...
My lazy bone wanted to do just one set of tests but this is the safer approach
I'll try to do my best to squeeze the POSTMAN tests today but this might be tight as I have a plane in a few hours and :sweat_smile:

**Comment by franck-boullier** [comment]
Just to make sure I get it right: AFAIK, this seems to behave as it should and the only thing left to test is the end to end test with the lambda right?
The Postman test will only allow me to see the behavior when a case is updated via Postman, not the lambda correct?

**Comment by nbiton** [comment]
The postman request simulates exactly what the lambda does. From MEFE's perspective, both types of interaction are exactly the same.

Suggestions for tests to run with postman:
* Post a "case_new_message" payload
* Post a "case_updated" payload
* Post any other type of payload (should not create an in-app notification marker)
* Post message/update to case that is in the bottom of the list
* Post to a case that is the top of the list and has notifications
* Post to case that has notifications, but is not at the top of the list
* Post to a case that already has all its previous notifications "marked as read"
* Post multiple times to a single case and see that the message/update counts are updating properly

**Comment by franck-boullier** [comment]
@nbiton  I can't find the POSTMAN queries... Where should I look?

**Comment by franck-boullier** [comment]
Forget about it @nbiton I just found it!

**Comment by franck-boullier** [comment]
# Test done:

- Simulate 2 new notifications with Postman as leonel (Regina assigned to the case) for the same case
- log in as Leonel Check that the there is no notification for Leonel PASSED
- log out
- log in as Regina Check that the notification is visible for Regina PASSED
- Check that the notification icon is correct NOT SURE... The icon displayed is
image
- Check that the number next to the notification icon is correct PASSED

**Comment by franck-boullier** [comment]
# Another Test:
- Simulate 2 new 'case_new_message' notifications with Postman as leonel (Regina assigned to the case) for the same case
- Simulate 2 new 'case_updated' notifications with Postman as leonel (Regina assigned to the case) for the same case
- log in as Leonel Check that the there is no notification for Leonel PASSED
- log out
- log in as Regina Check that the notification is visible for Regina at the unit level FAILED
image
- Check that there is 2 different notification icons on the updated case FAILED
- Check that the number next to the notification icon is correct PASSED
image

@nbiton, not sure what's happening here.
Let me know if you need more information about what I did

**Comment by nbiton** [comment]
I just tested as "Regina".
screenshot from 2018-07-14 18-51-53

I had to post another payload with postman previous to this, but I could see what you tried to post and I suspect it didn't work for you since you used "Deadline" as "update_what".
"Deadline" is not in the white list of fields which we produce in-app and email notifications for.
The values that are in the white list are:
```
[
  'Unit',
  'Role',
  'Component',
  'Product',
  'Severity',
  'Priority',
  'Platform',
  'Case Category',
  'Summary',
  'Next Step',
  'AssignedTo',
  'Resolution',
  'Status',
  'CC'
]
```

**Comment by franck-boullier** [comment]
Ah!
Ok
Good news then!
And the icon thing looks good.

Do you need me to do more tests?
As far as I'm concerned this looks OK to merge...

**Comment by nbiton** [comment]
Let's merge then

**Pull request merged**
