### PR TITLE
Sign inspection report

### PR DESCRIPTION
**Pull request by nbiton**
Fully working flow, up until the point of "Share report" (that is not a part of this PR)
Also, in contrast to the design, the current implementation uses all the unit's role users to be shown on the signage page, and does not allow to invite additional users yet (that feature will be added in a separate PR)

### CODE REVIEW

**Comment by franck-boullier** [comment]
@nbiton if everything is working as intended, is it OK to merge this one?

**Comment by nbiton** [comment]
Yup

**Comment by franck-boullier** [comment]
Bug: Impossible to access a report: clicking on the link to the report does nothing
(Samsung galaxy S8 - Chrome)

**Comment by franck-boullier** [comment]
More info on the bug:

# Works as intended:

Report are accessible if you go to the report via the 'Unit" page
Ex: https://unee-t-pr-500.herokuapp.com/unit/283/reports
Clicking on a report here display the report

# Does NOT work as intended:

Report are NOT accessible if you go to the report via the "Report" page
https://unee-t-pr-500.herokuapp.com/report
Clicking on a report here does Nothing (my guess is that the link has not been updated there)

**Comment by franck-boullier** [comment]
Signature flow works great!!

# One minor issue:
After the report is finalized and signed, report preview is displayed with the signatory
- Name
- Signature
- Role in the unit

## Actual result:
The role displayed for the signatory of the report is marked as "Administrator"

## Expected result:
The role displayed here is the role for the user for this unit

image

**Comment by nbiton** [comment]
> Report are NOT accessible if you go to the report via the "Report" page

That was fixed by `feat: fixed routes to report on the list explorer view`

> The role displayed for the signatory of the report is marked as "Administrator"

That was fixed by `fix: role resolving issue for report signature preview`

**Comment by franck-boullier** [comment]
This works as intended

Well done @nbiton!!!
We're almost there: need to fix the merge conflicts and this should be OK to merge

**Comment by franck-boullier** [comment]
Btw issue on the roles still seems to be there
See
https://unee-t-pr-500.herokuapp.com/report/62167/preview

**Comment by franck-boullier** [comment]
Sorry don't know how to attach a screenshot from my mobile 😅

**Pull request merged**
